name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/emu/android

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Sign APK
      id: sign-android-app
      uses: r0adkll/sign-android-release@v1.0.4
      with:
        releaseDirectory: ./src/emu/android/app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}

    - name: Compute git short sha
      id: git_short_sha
      run: echo "::set-output name=value::$(git rev-parse --short HEAD)"

    - name: Rename APK
      run: |
        mv ${{ steps.sign-android-app.outputs.signedReleaseFile }} eka2l1-${{ steps.git_short_sha.outputs.value }}.apk
        cp eka2l1-${{ steps.git_short_sha.outputs.value }}.apk android-latest.apk
      working-directory: ${{ github.workspace }}

    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: eka2l1-${{ steps.git_short_sha.outputs.value }}
        path: eka2l1-${{ steps.git_short_sha.outputs.value }}.apk

    - name: Update the CI tag
      uses: Xotl/cool-github-releases@v1
      with:
        mode: update
        isPrerelease: false
        tag_name: continous
        release_name: "Automatic CI builds"
        body_mrkdwn: |
          _This is the newest build, but Github date can't be updated. Corresponding commit: ${{ github.sha }}_
        assets: android-latest.apk
        replace_assets: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
      if: github.ref == 'refs/heads/master'
